#!/usr/bin/env python3
import argparse,gzip,json,re,sys
from pathlib import Path
from collections import Counter
sys.path.insert(0,str(Path(__file__).resolve().parent))
from machine_accounting_pilot_lib import sha256,git_blob_sha1,load_sharded,load_migration,expand_state,classify_fixture
A='87d5a7531b5e2b3841fe4ba093a87dd9da11e8c85b5d4184c6ae705436c1833e';B='ba9c660cf6f229ec2b19f024b9bc2cef94d26a44';D='e0087ccbb3460df384469b8a91ab4b412dce3e8d4ebd5a5833aa25dc7e74e667'
def main():
 ap=argparse.ArgumentParser();ap.add_argument('--repo-root',type=Path,default=Path('.'));ap.add_argument('--out',type=Path);a=ap.parse_args();r=a.repo_root;p=r/'data/pilot/f1';g=r/'generated/pilot/f1';checks={}
 def ck(n,c,d=None):checks[n]={'pass':bool(c),'detail':d};assert c,f'{n}: {d}'
 compact,_=load_sharded(p/'source_state_compact');s=[expand_state(x) for x in compact];e,_=load_sharded(p/'source_action_edges_compact');c,_=load_sharded(p/'validation_claims');v,_=load_sharded(p/'source_anchor_coverage');m,mi=load_migration(p/'migration_manifest');bind=json.loads((p/'action_table_binding.json').read_text());mem=json.loads((p/'membership_snapshot.json').read_text());prog=json.loads((g/'progress_summary.json').read_text());unk=json.loads((g/'unknown_debt.json').read_text());rt=json.loads((g/'roundtrip_result.json').read_text());f=json.loads((r/'tests/fixtures/machine_accounting_cardinality.json').read_text())
 text='\n'.join(json.dumps(x,sort_keys=True) for seq in(s,e,c,v) for x in seq);ck('fixture_prefix_absent','FIXTURE-' not in text);rel=classify_fixture(f);ck('fixture_cardinality',rel==f['expected'],rel)
 ck('sources_278',len(s)==len({x['source_id'] for x in s})==278);ck('revision1_migration',all(x['revision']==1 and x['changed_by']['type']=='MIGRATION' for x in s));ck('resolved_262',sum(x['target_status']=='RESOLVED' for x in s)==262);ck('analyzed_unresolved_16',sum(x['analysis_state']=='ANALYZED_UNRESOLVED' for x in s)==16);ck('closed_158',sum(x['closure_state']=='CLOSED' for x in s)==158);ck('blockers',Counter(x['blocker'] or 'NONE' for x in s)==Counter({'NONE':158,'PADDING_RECONSTRUCTION_REQUIRED':75,'SHARED_OWNER_BINDING_REQUIRED':25,'TERMINATOR_CAPACITY_FAIL':4,'F1_RULE_REJECTED_MIN_FINAL_INTERVAL':16}));ck('no_exclusions',all(x['exclusion_claim_id'] is None and x['applicability_state']=='APPLICABLE' for x in s));ck('candidate_only_rejected',all((x['target_identity'] is None and x['candidate_target_identity']) if x['analysis_state']=='ANALYZED_UNRESOLVED' else x['target_identity'] for x in s))
 mp=r/bind['canonical_action_manifest'];raw=mp.read_bytes();ck('action_file_hash',sha256(raw)==bind['manifest_file_sha256']);ub=gzip.decompress(raw);ck('action_content_hash',sha256(ub)==bind['manifest_content_sha256']);acts=[json.loads(x) for x in ub.decode().splitlines() if x.strip()];ck('actions_158',len(acts)==158);pairs=[(x['source_id'],x['authorization_action_id']) for x in acts];ep=[(x['source_id'],x['action_id']) for x in e];ck('edges_match_manifest',ep==pairs);h=sha256('\n'.join(x[0] for x in ep).encode());ck('authorized_hash',h==A,h);closed={x['source_id'] for x in s if x['closure_state']=='CLOSED'};ck('actions_only_closed',{x[0] for x in ep}==closed);ck('no_placeholder_actions',not({x['source_id'] for x in s if x['closure_state']=='OPEN'}&{x[0] for x in ep}));ck('shared_handoff',all(x['handoff_family']=='SHARED_OWNER_BINDING' for x in s if x['blocker']=='SHARED_OWNER_BINDING_REQUIRED'));ck('family_write_denominator',prog['write_authority_by_responsible_family']['F1_LOCALIZATION_STATIC_DIRECT']=={'responsibility_denominator':158,'authorized':158,'blocked_or_open':0})
 bf=Counter();br=Counter();blocked=set()
 for x in s:
  for u in x['unknown_fields']:
   bf[u['field']]+=1;br[u['resolution_requirement']]+=1
   if 'WRITE_AUTHORIZATION' in u['blocks']:blocked.add(x['source_id'])
 ck('unknown_fields',dict(bf)==unk['by_field'],dict(bf));ck('unknown_requirements',dict(br)==unk['by_resolution_requirement']);ck('unknown_blocks_write',all(x['write_authority']!='AUTHORIZED' for x in s if x['source_id'] in blocked));ck('unknown_expected',bf==Counter({'owner_binding':25,'target_identity':16}))
 ids=[x['claim_id'] for x in c];ci=set(ids);ck('claim_ids',len(ids)==len(ci) and all(re.fullmatch(r'V\d{3}\.C\d{2}',x) for x in ids));ck('claim_scope',all(88<=int(x['ledger_id'][1:])<=95 for x in c));ck('claim_deps',all(d in ci for x in c for d in x['depends_on_claims']));ck('negative_knowledge',any(x['claim_type']=='EVIDENCE_GAP' for x in c));ck('boundary_claims',any(x['claim_type']=='BOUNDARY' for x in c))
 doc=(r/'docs/F1_LOCALIZATION_SEQUENCE_AUDIT.md').read_bytes();ck('doc_git_blob',git_blob_sha1(doc)==B);ck('doc_sha256',sha256(doc)==D);lines=doc.decode().splitlines(keepends=True);reb=[];n=1
 for x in sorted(v,key=lambda z:z['block_ordinal']):
  ck('contiguous_'+x['coverage_id'],x['line_start']==n);t=''.join(lines[x['line_start']-1:x['line_end']]);reb.append(t);n=x['line_end']+1;ck('block_'+x['coverage_id'],sha256(t.encode())==x['block_sha256'])
 ck('coverage_eof',n==len(lines)+1);ck('coverage_no_unexplained',all(x['coverage_status']!='UNEXPLAINED' for x in v));ck('assertions_covered',all(not x['assertion_bearing'] or x['coverage_status']=='EXTRACTED' for x in v));ck('coverage_provenance',all(x['claim_refs'] or x['legacy_evidence_refs'] for x in v if x['coverage_status']=='EXTRACTED'));ck('coverage_refs',all(z in ci for x in v for z in x['claim_refs']));reb=b''.join(x.encode() for x in reb);ck('roundtrip',reb==doc and sha256(reb)==rt['source_sha256']);ck('roundtrip_diff_zero',rt['unexplained_roundtrip_diff_count']==0);ck('anchor_unexplained_zero',rt['unexplained_blocks']==0)
 exp={'SOURCE_STATE':{x['source_id'] for x in s},'ACTION':{x['authorization_action_id'] for x in acts},'SOURCE_ACTION_EDGE':{f'{x["source_id"]}->{x["action_id"]}' for x in e},'VALIDATION_CLAIM':ci,'SOURCE_ANCHOR_BLOCK':{x['coverage_id'] for x in v}};ck('migration_complete',mi['total_entries']==697 and all(set(m[k])==z for k,z in exp.items()),{k:len(z) for k,z in m.items()});ck('membership_total',mem['total']==278 and sum(mem['category_counts'].values())==278)
 gates={'membership_preservation':checks['sources_278']['pass'] and checks['authorized_hash']['pass'],'provenance_preservation':checks['migration_complete']['pass'] and checks['claim_deps']['pass'],'blocker_meaning_preservation':checks['blockers']['pass'] and checks['shared_handoff']['pass'],'source_action_cardinality_preservation':checks['edges_match_manifest']['pass'] and checks['fixture_cardinality']['pass'],'no_silent_unknown_pass':checks['unknown_blocks_write']['pass'],'unexplained_roundtrip_diff_zero':checks['roundtrip_diff_zero']['pass'],'source_anchor_unexplained_zero':checks['anchor_unexplained_zero']['pass']};ck('seven_gates',all(gates.values()),gates)
 result={'schema':'MACHINE_ACCOUNTING_PILOT_VALIDATION_V0_1','result':'PASS','seven_gates':gates,'counts':{'sources':278,'actions':158,'edges':158,'claims':len(c),'coverage_blocks':len(v),'migration_entries':mi['total_entries']},'checks_passed':sorted(k for k,z in checks.items() if z['pass'])};t=json.dumps(result,indent=2,sort_keys=True)+'\n';print(t,end='');
 if a.out:a.out.parent.mkdir(parents=True,exist_ok=True);a.out.write_text(t)
if __name__=='__main__':main()
